### ISSUE TITLE
Bitte um Prüfung Implementieren eines Streamunterstützungs Script + Server Key+

### ISSUE THREAD

**Issue by SirBassi** [OperationPandoraTrigger/OPT-Server-Mod#200]
Frozen-byte bat mich das als Pull Request einzustellen aber da ich noch dabei bin mich in github einzuarbeiten wollte ich mich nicht direkt in den Code "einklinken" und eröffne das Anliegen als eine Issue Medlung mit Bitte um Prüfung.

Details bitte der .txt entnehmen.

Vielen Dank vorab.

[Dokumentation.txt](https://github.com/OperationPandoraTrigger/OPT-Server-Mod/files/7010229/Dokumentation.txt)

**Comment by Frozen-byte** [comment]
du kannst dich einfach ungestört in den Code einmischen. 

Das Git-System ist so konzipiert, dass nichts kaputt oder verloren geht :)

**Comment by GNCLORD-MDB** [comment]
Ist das Linux Kompaktbibel ?

**Comment by Frozen-byte** [comment]
ja, auf dem Server wird nur der Key benötigt.

**Comment by GNCLORD-MDB** [comment]
no, Bibliothek Visual C++ Redistributable for Visual Studio 2015

**Comment by SirBassi** [comment]
Das ist richtig, auf Serverseite benötigen wir: Visual C++ Redistributable for Visual Studio 2015, Key aus dem URLFetch Git und das initplayerlocal Script im Hauptpfad der Missions PBO. Das der OPT Server auf Linux läuft wusste ich nicht als wir uns da Gedanken gemacht haben und entsprechend habe ich es auch nur auf eigenem Win19 Server getetestet. Ich habe bei Linux wirklich gar keine Erfahrung aber gibt es die Visual Bibliotheken nicht auch für Linux Server?

**Comment by Frozen-byte** [comment]
Es gibt Mono-Libaries die das abbilden können. Aber das finden wir heraus, sobald wir testen.

Wenn auf dem Server **nur** der Key benötigt wird, kann die c++vs215 Abhängigkeit jedoch nicht nachvollziehen.
Nach meinem Verständnis sind wir von der Libary erst abhängig, wenn wir es als kompletten "Servermod" installieren.

**Comment by SirBassi** [comment]
Ja, das war ein Denkfehler meinerseits. Da der Code aus der initplayerlocal lokal ausgeführt wird muss die Visual Bibliothek auch nur auf dem Client Rechner vorhanden sein und bei mir ist das im ersten Test Win10 gewesen und war bereits vorhanden.

**Comment by formtapez** [comment]
Ist nun implementiert und läuft auf allen unseren Servern. Bitte testen.

**Comment by SirBassi** [comment]
Perfekt. Habe sowohl auf dem offenen Trainingsserver als auch auf dem SWORD Trainingsserver getestet und hat wunderbar funktioniert. Joinen sowohl ohne als auch mit der URLFetch Mod waren möglich und Umsetzung im OBS lief wie erwartet. Vielen Dank.

**Comment by Frozen-byte** [comment]
Super!
Wollen wir dieses Issue dann schließen, oder möchtest du erst die Doku irgendwo hinschreiben und dann das Issue schließen?

**Comment by SirBassi** [comment]
Ich schliesse den Issue, schreibe die Doku dann in den nächsten Tagen fertig und entweder stellen wir Sie einfach ins Forum für Interessierte, nehmen Sie mit in die Readme oder wie Ihr das für am optimalsten haltet. Ihr seid da besser drin. Vielen Dank fürs umsetzen .
