### ISSUE TITLE
Redefinition Namespace und Mod-Ordner

### ISSUE THREAD

**Issue by formtapez** [OperationPandoraTrigger/OPT-Server-Mod#29]
Wie in #28 bereits angesprochen sollten wir die Namen der Mod-Ordner für eine klarere Trennung zwischen Client- und Servermod anpassen. Desweiteren bedarf es einer Anpassung des Namespaces ("PBO-Prefix"). Ich empfehle eine identische Namensgebung analog zu den Ordnernamen.

**Comment by Krzmbrzl** [comment]
Man muss mal noch schauen, wo CLib das PATH macro überall verwendet. Wenn daraus keine SQF Identifier gebastelt werden, kann man da ein @ in den Prefix mit rein nehmen. Wenn doch, geht das nicht.

Zur Namenstrennung (was Variablen angeht) bringt es aber eigentlich nur was, den PREFIX zu ändern.

**Comment by formtapez** [comment]
Können wir das hier langsam bitte mal klären? Sonst ist doch irgendwie nix mehr zueinander kompatibel und es geht nichts vorran.

**Comment by Krzmbrzl** [comment]
Also soweit ich bisher gesehen hab, sollte eine entsprechende Änderung möglich sein. Ausm Bauch raus würde ich es zwar nicht machen (Ich sehe noch keine inherenten Vorteile davon, den Prefix an die Ordnerstruktur anzupassen), aber per se sollte es möglich sein.

**Comment by formtapez** [comment]
Der Änderungswunsch hat sich aufgrund https://github.com/OperationPandoraTrigger/OPT-Client-Mod/pull/25 erledigt.
