### ISSUE TITLE
TFAR Intercom for Light Vehicles

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Server-Mod#32]
Alle Vehicles should get an TFAR Intercom:
Quilin, Ifrit, Hunter, Prowsler, Quad, etc.
How to enable intercom: https://opt4.net/forum/index.php?thread/3173-anpassungen-aus-dem-konzeptteam-heraus-f%C3%BCr-den-opt-mod-client-mod/&postID=60739#post60739

OP: https://opt4.net/forum/index.php?thread/2630-tfar-intercom-f%C3%BCr-ifrit-hunter

**Comment by Frozen-byte** [comment]
wrong repo.

**Comment by WGPSenshi** [comment]
See https://github.com/OperationPandoraTrigger/OPT-Client-Mod/issues/4
