### ISSUE TITLE
Tools weiter zentralisieren

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#36]
Die Build-Skripte sollten weiter zentralisiert werden.
Ultimatives Ziel ist es, einen "One-Click-Rebuild" zu ermöglichen.

Dafür müssen folgende Schritte erfolgen:

- Stop client & server
- Rebuild client mod
- Rebuild server mod
- Rebuild mission
- Put all files where they should be (metadata-based)
- Restart server & client

Wichtig dabei ist, dass die Mission an zwei Ziele verschoben wird: Die gebaute PBO muss AFAIK in den Arma 3\MPMissions-Ordner, damit der Server sie auch starten kann.
Zusätzlich sollte bei jedem "Build Mission"-Schritt der Missionsordner selbst (ungepackt) in einen metadata-Pfad in den Documents gespeichert werden, damit man auch per Editor direkt Zugriff darauf hat.

In der Konfig müssen also folgende Pfade angegeben werden:
- Arma-Ordner
- Documents/Profile-Ordner (z.B. C:\Users\Senshi\Documents\Arma 3 - Other Profiles\[WGP]Senshi\mpmissions)
- Mod-Zielordner (falls Subordner)
- Mod-Parameter (falls Subordner)

All diese Tools sollten aus allen Repos gleichzeitig zu erreichen sein. Insofern müssen sie entweder überall identisch gespiegelt werden, oder wir richten vielleicht doch einfachheitshalber ein eigenes Tools-Repo ein, um dieses Hickhack zu vermeiden.

Bitte diskutieren.

**Comment by Frozen-byte** [comment]
Dann wohl doch ein neues Repo und mit Submodul arbeiten. Alternative wäre die verschiedenen Repos zusammen zu legen und mit einem Monorepo zu arbeiten.

**Comment by Krzmbrzl** [comment]
Ich denke ein zentrales Repo für die Skripte ist am Besten. Dann kann zB auch die armake Version ganz einfach geupdatet werden

**Comment by formtapez** [comment]
Eigenes Tools Repo wäre gut. Aber dann brauchen wir keine Submodules wie @Frozen-byte sagte.

**Comment by formtapez** [comment]
Ein Monorepo hätte aber auch ein paar schicke Vorteile:

1. Scripte finden stets die richtigen Locations für Client, Server, Mission. Es brauchen keine Pfade konfiguriert zu werden.
2. Man hat stets ein passiges Gesamtpaket wenn man sich das Repo clont.
3. Issues, Canban, Projekte, Wiki usw. sind zentral verwaltbar und man braucht sich nicht erinnern in welchem Repo das nun liegt.
4. Versionsbezeichnungen in Client-, Server- und Missions- PBO-Dateinamen wären immer identisch.

**Comment by Krzmbrzl** [comment]
Da es sich aber um getrennte Projekte handelt (Mission, Client- und Servermod) halte ich ein Monorepo für unpassend. Das wird dann nur unnötig groß...

Wie geht das ohne Submodule @formtapez? :thinking:

**Comment by formtapez** [comment]
Naja, wenn ein Scriptpaket "alles" bauen soll, dann wird es ja zentral gestartet und muss wissen wo die einzelnen Repos liegen. Die Notwendigkeit, das als Submodul in den einzelnen Repos einzubinden, ist damit nicht mehr gegeben.

**Comment by WGPSenshi** [comment]
Einmal ein paar Pfade zu konfigurieren stört gar nicht. Dann bleibt es auch mit jedem Workflow kompatibel. :)

Bin zwar auch kein großer Fan von Monster-Repos, aber würde auch die Multi-PRs obsolet machen (z.B. Beam, welches einen PR für Client- und Servermod braucht). Da sehe ich aber das Multi-PR trotzdem noch als kleineres Übel.
