### ISSUE TITLE
remove 100Rnd mags from non CAR-95-1 / SPAR-16S variants 

### ISSUE THREAD

**Issue by gelir95** [OperationPandoraTrigger/OPT-Server-Mod#37]
Basic variants need a custom magazineWell.

**Comment by GNCLORD-MDB** [comment]
Nächsten das bitte auf Russisch, damit ich besser verstehe :-(
Ich vermute mal das soll heißen das die Standart Gewehre kein 100er Magazin laden können

**Comment by Frozen-byte** [comment]
Korrekt, die doppelte Verneinung ist vielleicht etwas verwirrend:
https://translate.google.com/#view=home&op=translate&sl=auto&tl=de&text=remove%20100Rnd%20mags%20from%20non%20CAR-95-1%20%2F%20SPAR-16S%20variants.%0ABasic%20variants%20need%20a%20custom%20magazineWell.

**Comment by Krzmbrzl** [comment]
Ist das überhaupt Aufgabe der Server-Mod? Für mich klingt das iwie danach, dass das in die Client-Mod gehört :thinking:
