### ISSUE TITLE
spieler marker

### ISSUE THREAD

**Issue by oldLucke** [OperationPandoraTrigger/OPT-Server-Mod#43]
- [ ] werden nicht auf dem GPS angezeigt
- [ ] nach respawn bleibt eigener marker auf der karte am Todesort hängen und wird nicht mehr aktualisiert
- [ ] nach respawn hat eigener marker bei dritten die Beschreibung "Error: No Unit"
- [ ] es wird nicht mehr angezeigt das sich eine Person in einem Fahrzeug befindet
- [ ] dronen AI wird als spieler marker gezeigt

**Comment by WGPSenshi** [comment]
(Hoffentlich) gelöst mit https://github.com/OperationPandoraTrigger/OPT-Server-Mod/pull/51

**Comment by WGPSenshi** [comment]
Fahrzeuge (inkl. Drohnen) sind noch nicht implementiert, das kommt erst noch.
