### ISSUE TITLE
GPS name Probleme

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#45]
Nach noch nicht reproduzierbarem Event / längerer Spielzeit:

Log wird hiermit vollgespammt (Unit name unterscheidet sich je nach Problemfall, können auch mehrere durcheinander sein).

22:10:34 WARNING: Function 'name' - CSAT_Offizier has no unit
22:10:34  - network id 2:7635
22:10:34  - person 
22:10:34  - dead

Und ab da treten die in #7 gemeldeten Probleme auf. Da läuft dann alles durcheinander.

Ideen, @Krzmbrzl ? Bzw. Idee für Workaround?
Im regulären Log taucht leider nix auf, kein Error oder sonstwie. Alle suchen nach dem Fehler weisen nur auf kryptische Engine-Bugs hin, die es wohl schon ewig gibt. Bin mir aber nicht sicher, wie man jetzt am besten einen Workaround bzw. "Catch" für diese Situation einbaut.

Wissen auch noch nicht, was und wann es getriggert wird. Super ätzend :/ .

Bisher haben wir es nur durch einen Missionsrestart gefixt bekommen.

**Comment by Krzmbrzl** [comment]
Also nach dem was ich im BIKI zu `name` gelesen hab in Kombination mit diesen Log-Einträgen, bin ich mir ziemlich sicher, dass tote Einheiten nicht rihtig aus dem GPS entfernt werden.

`name` wird allerdings nur an einer einzigen Stelle im Code verwendet (gemäß GitHub-Suche):
https://github.com/OperationPandoraTrigger/OPT-Server-Mod/blob/7764b288a290079e2f701b364cc72434b992e081/addons/OPT/GPS/fn_addUnitToGPS.sqf#L95

Dementsprechend wäre es interessant, ob das Problem (oder zumindest die Log-message) nur auftaucht, wenn man eine Beschreibung der EInheit anzeigen lässt (entweder weil sie permanent angezeigt wird, oder eben beim mouseover).

Die einzige Stelle, an der Einheiten aus dem System entfernt werden, scheint in der `init` der SM zu sein:
https://github.com/OperationPandoraTrigger/OPT-Server-Mod/blob/adbe0050188f53bc06cab823b40951776eaad604/addons/OPT/GPS/fn_clientInit.sqf#L50-L55

Ich würde also mal versuchen, einen `Killed`-EventHandler zu installieren (gibts von CLib: https://github.com/TaktiCool/CLib/wiki/Events), der Einheiten sofort nach ihrem Tod aus dem System entfernt. Denn bis die SM wieder dazu kommt Einheiten zu entfernen kann es ja ne Weile dauern und wenn SQF-Fehler (wie der von `name`) dazwischen kommen weiß man ja nie, was Arma so alles anstellt...

Darüber hinaus würde ich auch mal versuchen die Beschreibung komplett zu deaktivieren (also den gesameten damit zusammenhängenden Code auskommentieren) und schauen, ob das Problem dann immernoch auftritt.

**Comment by WGPSenshi** [comment]
Problemquelle hast du richtig erkannt, es beginnt immer dann, wenn eine Einheit stirbt. Aber random, nicht unter replizierbaren Umständen. Haben da schon viel versucht.

Aber kurios, dass das Problem auch dazu führt, dass auf dem GPS plötzlich gar keine Marker mehr gerendert werden. Irgendwie fühlt es sich an, als ob da einiges aus dem Takt gerät.

Wie würde ich denn die Unit hart aus der Liste entfernen, ohne die SM ins Stolpern zu bringen? Momentan ist das alles ja ein recht autarkes System. Müsste aus dem unit-Name den richtigen Icon-Name generieren und dann removen. 🤔

**Comment by WGPSenshi** [comment]
Vielleicht so? Ganz unten, direkt bei clientInit, so dass er garantiert mitläuft?
```

["Killed", {
	params ["_unit", "_killer", "_instigator", "_useEffects"];
    
    private _iconId = toLower format [QGVAR(IconId_Player_%1_%2), _unit, group _unit isEqualTo group CLib_Player];
    DUMP("ICON REMOVED BECAUSE KILLED: " + _iconId);
    [_iconId, "hoverin"] call CFUNC(removeMapGraphicsEventHandler);
    [_iconId, "hoverout"] call CFUNC(removeMapGraphicsEventHandler);
    [_iconId] call CFUNC(removeMapGraphicsGroup);

}] call CFUNC(addEventhandler);
```

**Comment by Krzmbrzl** [comment]
Jo schaut mal ganz gut aus - allerdings müsste das glaub `_this select 1 parans [...]` heißen, da CLib Events glaube ich immer als ersten parameter die ID des Handlers oder sowas mit bekommen :thinking: 

> Auf der anderen Seite sollte er ja auch nur laufen, solange eine Map/Minimap offen ist.

Nö - es schadet ja nicht tote Einheiten tdem aus dem System raus zu nehmen. Und da das Eventbasiert ist, sollte das kaum overhead erzeugen.

> Wie würde ich denn die Unit hart aus der Liste entfernen, ohne die SM ins Stolpern zu bringen? 

Das ist die große Frage. Wenn die EInheit bereits mit einem Marker vershene wurde, sollte der gepostete Code ausreichen. Wenn aber eine Einheit in der "SM-Queue" (also in dem `_unit`-Array das von der SM rum gereicht wird) stirbt, dann muss die EInheit aus dieser Queue raus genommen werden (oder die SM checkt jede Einheit auf ihr Lebenszeichen, bevor sie den Marker hinzufügt - macht sie das nicht sogar schon?)

**Comment by Krzmbrzl** [comment]
> Aber random, nicht unter replizierbaren Umständen. Haben da schon viel versucht.

Habt ihr schon die Logs der Personen aufgetrieben, bei denen es gespackt hat?

**Comment by WGPSenshi** [comment]
Jo, in denen steht aber rein gar nix auffälliges drin, außer eben dem "no unit"-spam

**Comment by WGPSenshi** [comment]
Der vollständigkeit halber:
https://github.com/michail-nikolaev/task-force-arma-3-radio/issues/1096

Spannend:
"The name command cannot be used in the frame the unit is created. This includes respawning.
The best would be to completely avoid relying on name (or vehicleVarName for that matter) in scripting and only use object references."

Das klingt auch obskur genug, um eben nur gelegentlich zu Problemen zu führen.

Also müsste ich wohl dafür einen Workaround bauen. Spielernamenliste, synchronisiert bei jedem OnConnected/Disconnected mit allen? Ist ja auch bissl blöd.

**Comment by GNCLORD-MDB** [comment]
Alle anderen Versuche über Spielernamenpools , Trackinglisten oder sonstige versuche Namen mit Spieler zu koppeln haben wir alle schon durch in der OPT und die haben nie zufriedenstellen funktioniert. 

Es bleibt nix anderes übrig alle mehrfach den Namen zu checken und zu setzen.

**Comment by Krzmbrzl** [comment]
Sehr einfache Lösung des Problems: Die Marker SM muss eventbasiert werden und das Event für neue Einheiten wird via execNextFrame um ein frame verzögert (oder Vllt um sicher zu gehen gleich um 3-5 oder so)

**Comment by WGPSenshi** [comment]
Weiß nicht ob das so trivial ist. Würde heißen, dass wir doch wieder selbst Events global schicken müssen, oder? Weder Respawn noch MPRespawn sind Effect global. Am Ende müssten wir mindestens auf Killed, Respawn, OnConnect/Disconnect lauschen, um auf jeden Fall alles konsistent zu halten. Genau das war ja der Charme der SM, diese neuen möglichen Stolperfallen zu vermeiden. Als ich das letzte Mal mit diese Events gearbeitet hatte, gab es auch da praktische Problemchen.

**Comment by Krzmbrzl** [comment]
Killed und Respawn reicht, wenn du via description.ext festlegst dass das initiale connecten auch als Respawn gewertet wird.

Vorteil der SM ist ein abfedern der Last auf verschiedene Frames wenn viele auf einmal respawnen/sterben.

Was für Probleme hattest du da? :thinking:

**Comment by WGPSenshi** [comment]
Das deckt dann nur die einfachen Einheitenmarker ab. Es sollen ja auch Gruppen- und Fzg-Marker dazukommen, die ja auch removed/added werden müssen, je nachdem was die Spieler so tun. Gruppenmarker ist relativ easy (hängt immer beim Groupleader, außer er sitzt im Fzg).
Bei Fzg-Markern wird der Gruppenmarker dann wieder anders gehandhabt (falls mehrere Gruppen im Fzg sitzen). Gleiches mit Gruppen-Hover. Und Uniticons werden natürlich entfernt, wenn man im Fzg sitzt.

Dann bräuchte es noch GetIn/GetOutMan, und besonderes Handling, wenn einzelne Leute im Fzg sterben bzw. das Fahrzeug selbst gekillt wird.

**Comment by Krzmbrzl** [comment]
Den entsprechenden Code bräuchtest du aber ja ohnehin. Ob du den jetzt innerhalb der SM oder in einen EH schreibst, ist doch eig egal, oder? Mit EHs hast du halt den Vorteil, dass du nicht dauernd Sachen übrerprüfst/neu machst, die sich nicht geändert haben und wenn sich was ändert, kannst du genau in diesem Moment darauf reagieren und nicht erst wenn die SM mal wieder bei der entsprechenden Einheit vorbei schaut :thinking:

**Comment by WGPSenshi** [comment]
Der entsprechende Code ist ein simpler "in vehicle"-Check, der jedes Mal beim init-step abgefragt wird.
Die GetIn(Man)/GetOut(Man)-EHs sind halt wieder nur lokal zuverlässig. Müsste ich also auch wieder jedes Mal global einen Methodenaufruf triggern (remoteExecCall), und bei denen bin ich mir nie sicher, ob sie 100% zuverlässig sind. Z.b. Race-Issues kann ich mir da auch gut vorstellen. Beispiel: Spieler wird im Fzg getötet, was einen Eject triggert. Dabei werden zwei EHs ausgelöst: GetOut und isUnconscious (custom EH). GetOut sorgt dafür, dass überhaupt ein Unitmarker gezeichnet wird, während isUnconscious den Marker auf Verwundet ändert. Geht aber natürlich nur, wenn der Marker schon existiert. Gleiches kann für viele andere Kombinationen passieren (Respawn aus Fahrzeug etc.) .

**Comment by Krzmbrzl** [comment]
> Die GetIn(Man)/GetOut(Man)-EHs sind halt wieder nur lokal zuverlässig

Quelle? Das wäre mir nämlich neu... Prinzipiell sollte es ja gehen dass du auf jedem Client die entsprechenden EHs an die entsprechenden Einheiten klebst. Dann sollten auch race-comditions unmöglich sein, da SQF ja nicht parallel und in diesem Fall ja auch nur auf einem einzigen Client läuft.

**Comment by WGPSenshi** [comment]
https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetIn

**Comment by Krzmbrzl** [comment]
> Triggers when a unit enters a vehicle. It can be assigned to a remote vehicle but will only fire on the PC where the actual addEventHandler command was executed.

Du meinst das? Das bedeutet (nach meine Verständnis - wobei ich mir da aber halbwegs sicher bin) dass du den EH auf jedem beliebigen Client an jedes beliebige Objekt hinzufügen kannst. Der Code wird aber nur auf dem Client ausgeführt, auf dem der EH hinzugefügt wurde und nicht auf dem Client zu dem das Objekt lokal ist. Das bedeutet, dass du nicht auf dem Server an jeden Spieler einen EH setzen kannst, der zB einen hint ausgibt, da der EH dann auch nur auf dem Server ausgeführt wird und somit kein einziger Spieler was von dem hint mit bekommet.

> Auch das "Persistent on respawn if assigned where unit was local." bei GetInMan ist kurios, finde ich.

Kurios auf jeden Fall, aber ich denke das heißt nichts anderes, als dass du den EH an den lokalen Spieler nur ein einziges Mal setzen musst und Arma den EH beim Respawn dann auf die neue Einheit überträgt. Das würde ich aber auf jeden Fall testen, bevor ich mich darauf verlassen würde...

**Comment by WGPSenshi** [comment]
Tue mir echt schwer, das Event-Konstrukt aufzubauen.

Respawn/Killed muss ich an alle Spieler hängen.
Wie bekommt jeder Client mit, wenn andere Spieler dazu kommen? `onPlayerConnected`/ 'handleDisconnect' gibt's nur für Server. Also müsste ich dann entweder pVs/remoteExec an die Spieler raushauen und Server & Netzwerk belasten, oder - wenn es lokal sein soll - müsste ich stumpf mittels PFH `allPlayers` auf Änderungen überwachen und dann die entsprechenden Events auslösen. Das ist für die Performance aber auch nicht der Bringer, und führt das "eventbasiert" auch irgendwie wieder ad absurdum.
Ganz zu schweigen davon, dass onPlayerConnected auch keine unit-Referenz bietet, das also auch erst noch mit `owner` etc. abgefragt werden muss.

Also doch bei jedem Spieler lokal ein onRespawn/Killed, und dann wieder pV/remoteExecCall mit potentiellen Races?

Keine Ahnung, was die sinnvollste Variante ist. Oder gibt's noch einen Ansatz, der mir nicht einfällt?

**Comment by GNCLORD-MDB** [comment]
Es gibt das vielleicht einen Weg ob der Besser ist las ich mal dahin gestellt von der Belastung her.
Wenn du will das nicht etwas dauern läuft und anspringt wenn sich etwas ändert.

1.du erstellt den onPlayerConnected Event in einen Server Script, das anspringt und eine zufällig Zahl an alle Client schickt per Publicvariable "check". 

2. Einen "Check" addPublicVariableEventHandler {}; einbauen der dann die Spieler aktualisiert auf den Client. 

So gibt es eine Automatische Erneuerung und alle Client haben den gleichen Kenntnis stand.

**Comment by WGPSenshi** [comment]
Genau das hab ich doch auch vorgeschlagen? Warum eine zufällige Zahl geschickt werden soll, erschließt sich mir aber nicht :D .

**Comment by GNCLORD-MDB** [comment]
damit den addPublicVariableEventHandler anspringt , der reagiert nur auf Änderungen der War die er beachtet.

**Comment by WGPSenshi** [comment]
Kannst genausogut boolean switchen (true/false). Wie gesagt, ist doch genau das was ich auch als eine Variante vorgeschlagen habe.

**Comment by GNCLORD-MDB** [comment]
ja habe ich so nicht verstanden :-)

**Comment by Krzmbrzl** [comment]
> Wie bekommt jeder Client mit, wenn andere Spieler dazu kommen?

https://github.com/TaktiCool/CLib/wiki/Events - da gibts ein `EntityCreated` Event, das zumindest dem Namen nach Respawn und (re-) connects abdecken sollte. Muss man mal ausprobieren.

> und dann wieder pV/remoteExecCall mit potentiellen Races?

Also wenn würde man dafür auch Events verwenden. CLib kann die ja auch von einem Client zu einem anderen auslösen (dafür nutzt es meines Wissens nach übrigens auch ein System, das auf `publicVariable` aufbaut).

**Comment by WGPSenshi** [comment]
entityCreated ist mit Kanonen auf Spatzen. Dahinter steckt ein Cache, der frühestens alle 15ms aktualisiert wird und `allmissionobjects "All"`(!) in einer SM durchgeht (um eben nicht zu blocken). Da ist eine selbstgebaute Schleife über allPlayers garantiert fixer und genauer.

**Comment by Krzmbrzl** [comment]
Diese Schleife läuft aber eh im Hintergrund (Referenz: https://github.com/TaktiCool/CLib/blob/65eb00e93b1f734b3f68133c84dabd1a6463c39e/addons/CLib/Events/fn_init.sqf#L274-L330). Dann kann man sie auch nutzen, anstatt selber nochmal ne extra Schleife zu machen Außerdem sind 15ms delay für so ein Marker-System glaube ich easy verschmerzbar :man_shrugging:

**Comment by WGPSenshi** [comment]
Problem kommt nicht von uns, sondern aus CBA, ACE oder TFAR...
