### ISSUE TITLE
GPS-Modul "vergisst" Displays

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#47]
Nachdem der andere Bug behoben ist, gibt es nun noch einen:

Nach wie gehabt nicht reproduzierbaren Schritten vergisst das Modul, die Marker auch auf dem GPS zu zeichnen. Auf der KArte geht noch alles, auf dem GPS/Minimap nicht mehr.

Anfangs geht alles tadellos, auch nach Reconnects.

TRitt der Bug aber einmal bei irgendjemand auf, so geht es bei den anderen dann maximal noch so lange, bis sie auch reconnecten. Nach einem Reconnet werden die Marker auf dem GPS einfach nicht mehr gezeichnet.

Ideen? @Krzmbrzl

**Comment by Krzmbrzl** [comment]
Gibt's iwas Reproduzierbares bei diesem Bug?

Ansonsten könnte man einfach bei jedem connect loggen, ob das Display für das GPS gefunden wird. Also einmal den connect selber loggen und dann analog zu dem Code in der init des MapGraphics Moduls aus CLib nach dem Display suchen und wenn gefunden einmal loggen... Vllt sieht man daran was faul ist...

**Comment by WGPSenshi** [comment]
Bisher trat er vermutlich gemeinsam mit dem No unit/name Bug auf. Sobald der einmal auftrat, gehen bei einzelnen oder mehreren der Reihe nach die Marker auf dem GPS verloren.

**Comment by Krzmbrzl** [comment]
Dann würde ich mal darauf tippen, dass das intern iwas in der engine verwurschtelt hat... Genauso wie Fehler in SQF zu komischen Zuständen führen können.

Aber dh der Fehler trat nach dem fix des name Bugs nicht mehr auf?

**Comment by WGPSenshi** [comment]
Doch, leider auch. :(

**Comment by WGPSenshi** [comment]
Gelöst mit https://github.com/OperationPandoraTrigger/OPT-Server-Mod/pull/51

**Comment by WGPSenshi** [comment]
Ist ja leider immer noch aktiv.

**Comment by GNCLORD-MDB** [comment]
geschlossen, da bearbeitet
