### ISSUE TITLE
GPS-Modul : Marker auf Artilleriecomputer zeichnen

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#48]
Der Ari-Computer hat keine feste displayid (-1), lässt sich also nicht als Mapcontrol registrieren. Wie würde man das am besten abfangen, um auch auf der Aricomputer-Karte die MArker zu zeichnen?

**Comment by GNCLORD-MDB** [comment]
Nutzt die Mapcontrol aus den meinen versucht da sind alle Mapcontrol dirn die wir benötigen

**Comment by GNCLORD-MDB** [comment]
dazu muss noch eine Event rein der bei jedem Öffnen die Mapcpntrol neu anmeldet.

**Comment by Krzmbrzl** [comment]
Ich hab dazu im Forum in dem Thread zum alten GPS schonmal was geschrieben. Arma zeigt zwar alles mit IDD -1 als `displayNull` an, aber man kann das tdem normal verwenden.
Man muss nur ein bisschen durch iterieren um ein Handle dafür zu bekommen...

**Comment by Krzmbrzl** [comment]
https://opt4.net/forum/index.php?thread/2854-opt-renew-%E2%80%8Blivetracker-dynamische-marker-darstellung/&postID=53379#post53379

**Comment by WGPSenshi** [comment]
Gelöst mit https://github.com/OperationPandoraTrigger/OPT-Server-Mod/pull/51
