### ISSUE TITLE
GPS Marker gelöschter Units werden weiter gezeichnet

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#60]
Marker von Einheiten, die nicht mehr existieren, werden manchmal weiter gezeichnet und "sammeln" sich im Lauf der Schlacht an Position 0/0 (weil getPos unit = 0/0).

Warum? Wo hängen diese Marker noch rum? MapGraphicsCache, MapGraphicsGroups?

Wie fängt man am besten ab, dass diese ordentlich entfernt werden (Event "unit deleted")?

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
