### ISSUE TITLE
GPS Defekt

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Server-Mod#62]
Nachjoiner haben kein funktionierendes GPS

https://opt4.net/forum/thread/4247-green-hell-schlacht-03-feedback/?postID=84406#post84406

**Comment by GNCLORD-MDB** [comment]
Bitte mal den GPS Fix einspielen um zusehen ob dieser Fehler dann auch verschwindet.

**Comment by Frozen-byte** [comment]
Welchen? Sehe hier kein Merge-Request verlinkt. So weiß ich nicht welcher MR dieses Problem behebt.

**Comment by GNCLORD-MDB** [comment]
Den muss ich nachher suchen, ist auf dem Handy schwer. Den wo es schon einen PR zu gibt der 2 Monate alte ist.

**Comment by GNCLORD-MDB** [comment]
Umbau GPS System #59

**Comment by Frozen-byte** [comment]
Ich kann das nicht mergen. Es sind noch unbearbeitete Anmerkungen dabei.

Es müssen erst alle Anmerkungen in dem Merge-Request bearbeitet werden, damit wir nicht mehr Bugs einbauen als wir mit dem Ticket versuchen zu lösen:  
![image](https://user-images.githubusercontent.com/3965439/83286985-28a77c80-a1e1-11ea-824d-8861804ab5a9.png)

**Comment by GNCLORD-MDB** [comment]
Wo fest den das was ich habe alles beantwortet. 
Ich finde da nix wo was offen ist.

**Comment by Frozen-byte** [comment]
> Wo fest den das was ich habe alles beantwortet.

Das stimmt nicht, hier hast du die ganz klar nicht beantwortet.
https://github.com/OperationPandoraTrigger/OPT-Server-Mod/pull/59/files/ec9c0880e58054877419e04446fc4e2194bd6f52


Auf die Antworten, die du gegeben hast, wurden bereit Antworten verfasst:  
https://github.com/OperationPandoraTrigger/OPT-Server-Mod/pull/59/files/4f4805e5c32629c2999774636ff2444496dc51e9

**Comment by GNCLORD-MDB** [comment]
Das ist alles beantwortet !
Ich weiß nicht was du da von mir willst.

https://www.directupload.net/file/d/5836/t54f2245_jpg.htm
https://www.directupload.net/file/d/5836/t54f2245_jpg.htm

**Comment by Frozen-byte** [comment]
das kannst nur du lesen Lord da steht ganz dick in gelb **"PENDING"** 
Du musst noch den rechts auf "Review Changes" klicken damit du dein Review auch absendest.

Nächstes mal vielleicht kein Review deines eigenen PRs anfangen, sondern einfach antworten :)

**Comment by GNCLORD-MDB** [comment]
Vielleicht auch erst gar keine unnötige Diskussionen beginnen und das ganze durchwinken nächsten :-)

Was weiß ich denn was pending bedeutet

**Comment by GNCLORD-MDB** [comment]
Frozen ich kann nix finden wo ich nun was klicken, abhaken oder sonst was machen kann.

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
