### ISSUE TITLE
Administrator kann den Fraktionen während der Schlacht mehr Geld auf das Konto überweisen

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Server-Mod#64]

**Comment by GNCLORD-MDB** [comment]
Das müss mal testen ob die CBA Setting nicht das jetzt schon zu lassen, wenn als Admin per Server Reiter neu das Geld setzt.

**Comment by Frozen-byte** [comment]
use  
`playersidechat format ["Geld:%1",OPT_GELDZEIT_csat_budget];`  
new absolut budget:  
`OPT_GELDZEIT_csat_budget = 000000;`  
`publicVariable "OPT_GELDZEIT_csat_budget";`

**Comment by GNCLORD-MDB** [comment]
> 
> 
> use
> `systemchat format ["Geld:%1",OPT_GELDZEIT_csat_budget];`
> new absolut budget:
> `OPT_GELDZEIT_csat_budget = 000000;`
> `publicVariable "OPT_GELDZEIT_csat_budget";`
