### ISSUE TITLE
Statistiken lauffähig machen

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Server-Mod#68]

**Comment by GNCLORD-MDB** [comment]
Wegen fehlender Doku, muss man testen und probieren was  noch fehlt.

**Comment by Frozen-byte** [comment]
@GNCLORD-MDB 
Wenn du mir zeigst wie der Log aussieht mache ich daraus vorläufig erstmal Statistiken bis HardieReady sich meldet.

Da müssen dann aber definitiv die "doppelt und dreifachen" Logeinträge raus.

**Comment by GNCLORD-MDB** [comment]
das sind die Logdaten von der Mission, da Fehlt nur noch Revive Einträge

2020/07/31, 18:20:33 "[OPT] (Mission) #################### opt_mission_103_fun3_test ####################"
2020/07/31, 18:20:49 "[OPT] (Budget) Log: 0:00:00 --- Startbudget: AAF:3e+006 - CSAT:3e+006"
2020/07/31, 18:20:49 "[OPT] (Budget) Log: 0:00:00 --- Beginn Waffenruhe: 2 min"
2020/07/31, 18:22:04 "[OPT] (Budget) Log: 0:01:15 --- AAF alt: 3e+006 - neu: 2.975e+006 - Differenz: -25000. [GNC]Lord-MDB (ver)kaufte MB 4WD (LMG)"
2020/07/31, 18:22:22 "[OPT] (Budget) Log: 0:01:33 --- AAF alt: 2.975e+006 - neu: 2.779e+006 - Differenz: -196000. [GNC]Lord-MDB (ver)kaufte WY-55 Hellcat"
2020/07/31, 18:22:35 "[OPT] (Budget) Log: 0:01:46 --- AAF alt: 2.779e+006 - neu: 2.691e+006 - Differenz: -88000. [GNC]Lord-MDB (ver)kaufte FV-720 Mora"
2020/07/31, 18:22:50 "[OPT] (Mission) Beginn Rest-Spielzeit: 11.3102 min"
2020/07/31, 18:22:50 "[OPT] (Fahne) Log: 0:02:01 --- Kein Dominator (AAF 0 | CSAT 0)"
2020/07/31, 18:23:02 "[OPT] (Budget) Log: 0:02:13 --- AAF alt: 2.691e+006 - neu: 2.683e+006 - Differenz: -8000. Fahrzeug FV-720 Mora wurde auf/abgerüstet von [GNC]Lord-MDB."
2020/07/31, 18:23:50 "[OPT] (Fahne) Log: 0:03:01 --- Kein Dominator (AAF 0 | CSAT 0)"
2020/07/31, 18:23:56 "[OPT] (Fahne) Log: 0:03:07 --- Dominator ist AAF"
2020/07/31, 18:23:56 "[OPT] (Fahne) Log: 0:03:07 --- AAF Flagge erobert von [GNC]Lord-MDB"
2020/07/31, 18:24:21 "[OPT] (Abschuss) Log: 0:03:32 --- Einheit: [GNC]Lord-MDB (side: GUER) von: Faisal Tanwir (side: EAST) (magazine: 30-Schuss-5.8mm-Magazin)"
2020/07/31, 18:24:50 "[OPT] (Fahne) Log: 0:04:01 --- AAF +1 (AAF 1 | CSAT 0)"
2020/07/31, 18:25:12 "[OPT] (Budget) Log: 0:04:23 --- AAF alt: 2.683e+006 - neu: 2.383e+006 - Differenz: -300000. [GNC]Lord-MDB (ver)kaufte AAF Sprengstoffkiste"
2020/07/31, 18:25:50 "[OPT] (Fahne) Log: 0:05:01 --- AAF +1 (AAF 2 | CSAT 0)"
2020/07/31, 18:25:55 "[OPT] (Transport) Log: 0:05:06 --- [GNC]Lord-MDB (GUER) wurde von Unbekannt (GUER) eingeflogen (7165.48 m)"
2020/07/31, 18:26:05 "[OPT] (Abschuss) Log: 0:05:16 --- Fahrzeug: WY-55 Hellcat (category: Flug) (side: OPT_AAF) von: [GNC]Lord-MDB (side: GUER)."
2020/07/31, 18:26:51 "[OPT] (Fahne) Log: 0:06:02 --- AAF +1 (AAF 3 | CSAT 0)"
2020/07/31, 18:27:16 "[OPT] (Fahne) Log: 0:06:27 --- CSAT Flagge erobert von [GNC]Lord-MDB"
2020/07/31, 18:27:43 "[OPT] (Budget) Log: 0:06:54 --- CSAT alt: 3e+006 - neu: 2.975e+006 - Differenz: -25000. [GNC]Lord-MDB (ver)kaufte Qilin (Unbewaffnet)"
2020/07/31, 18:27:51 "[OPT] (Fahne) Log: 0:07:02 --- Kein Dominator (AAF 3 | CSAT 0)"
2020/07/31, 18:28:51 "[OPT] (Fahne) Log: 0:08:02 --- Kein Dominator (AAF 3 | CSAT 0)"
2020/07/31, 18:28:53 "[OPT] (Fahne) Log: 0:08:04 --- Dominator ist CSAT"
2020/07/31, 18:28:53 "[OPT] (Fahne) Log: 0:08:04 --- CSAT Flagge gesichert von [GNC]Lord-MDB"
2020/07/31, 18:29:51 "[OPT] (Fahne) Log: 0:09:02 --- CSAT +1 (AAF 3 | CSAT 1)"
2020/07/31, 18:30:51 "[OPT] (Fahne) Log: 0:10:02 --- CSAT +1 (AAF 3 | CSAT 2)"
2020/07/31, 18:31:51 "[OPT] (Fahne) Log: 0:11:02 --- CSAT +1 (AAF 3 | CSAT 3)"
2020/07/31, 18:32:51 "[OPT] (Fahne) Log: 0:12:02 --- CSAT +1 (AAF 3 | CSAT 4)"
2020/07/31, 18:33:51 "[OPT] (Fahne) Log: 0:13:02 --- CSAT +1 (AAF 3 | CSAT 5)"
2020/07/31, 18:34:11 "[OPT] (Fraktionsübersicht) Log: 0:13:22 --- [GNC]Lord-MDB (GUER), PUID 76561197998700054"
2020/07/31, 18:34:11 "[OPT] (Mission) Log: 0:13:22 --- Missionzeit abgelaufen"
2020/07/31, 18:34:11 "[OPT] (Budget) Log: 0:13:22 --- Endbudget: (AAF:2.383e+006 | CSAT:2.975e+006)"
2020/07/31, 18:34:11 "[OPT] (Punkte) Log: 0:13:22 --- Endpunktestand: (AAF:3 | CSAT:5)"

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
