### ISSUE TITLE
GPS

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Server-Mod#7]
Einzelfunktion: Darstellen der Spieler auf der Karte mir Name,Status und Zusatzinfomaitonen.

Modus 1(Grundeinstellung)

Jeder Spieler sieht sich selbst
Der Spieler sieht alle Einheiten in seiner Gruppe
Der Spieler sieht alle Gruppenführer von seiner Seite
Der Spieler sieht alle Spieler die auf Revive warten.
Der Spieler bekommt angezeigt ob er in einem Fahrzeug sitzt
Modus 2(Offiziere)

Jeder Spieler sieht sich selbst 
Es werden alle Spieler der Seite angezeigt.
Der Spieler sieht alle Spieler die auf Revive warten.
Der Spieler bekommt angezeigt ob er in einem Fahrzeug sitzt

**Comment by GNCLORD-MDB** [comment]
mal in GPS ändern bitte

**Comment by GNCLORD-MDB** [comment]
Und erstelle dann auch mal wenn das so aufgeschlüsselt werden soll auch noch zwei issues für RADAR und Dynamische Markerverwaltung dann ist das Projekt komplett hier abgebildet.

**Comment by Frozen-byte** [comment]
Kommt, wenn sie gebraucht werden. Erstmal GPS.

**Comment by Krzmbrzl** [comment]
Also das erste, das gebraucht wird, ist die dynamische Markerverwaltung

**Comment by GNCLORD-MDB** [comment]
Einfach die 3 erstellen und gut ist

**Comment by Krzmbrzl** [comment]
@GNCLORD-MDB du solltest die auch selber erstellen können. Das muss niemand anderes für dich machen :)

**Comment by Frozen-byte** [comment]
API ist ebenfalls schon erstellt. Nur  Radar vermisst gerade niemand also können wir das zurück priorisieren

**Comment by GNCLORD-MDB** [comment]
und was ist das dann ein Feature request?

**Comment by Frozen-byte** [comment]
ein "Feature Request" ist ein Ticket welches eine neue Funktionalität fordert. Oder was meinst du?

**Comment by GNCLORD-MDB** [comment]
Man Leute ,wenn ich auch New Issue klicke kommt nur Feature Request oder Bug Report !

**Comment by Frozen-byte** [comment]
@GNCLORD-MDB mach einfach einen Pull-Request ich werde das dann schon zuordnen!
https://github.com/OperationPandoraTrigger/OPT-Mod/projects/1 hier sind API und RADAR ja bereits als Platzhalter drin.

**Comment by GNCLORD-MDB** [comment]
oki

**Comment by Krzmbrzl** [comment]
@GNCLORD-MDB Wenn du einen issue aufmachst kannst du unter dem Auswahlmenü über `Open a regular issue.` einen ganz normalen Issue aufmachen

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
