### ISSUE TITLE
nachdem einFahrzeug platzt stirbt die Besatzung nicht, sondern steigen aus.

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Server-Mod#74]
am coolsten wäre eine gewisse Wahrscheinlichkeit zu überleben aber keine 100%ige

**Comment by GNCLORD-MDB** [comment]
Das Phänomenhabe ich nur bei Gepanzerten Fahrzeuge gesehen bisher. 
Ich habe da noch nicht verstanden warum ACE den schaden ausblendet.   
Das könnte etwas fummlig wieder werden.

**Comment by GNCLORD-MDB** [comment]
ACE MEDIC BUG
https://github.com/acemod/ACE3/issues/7305
Wenn ich verstanden habe wie schwer der Bug ist kann ich vielleicht dagegen arbeiten mit einem Script

**Comment by GNCLORD-MDB** [comment]
Workaround Idee vorhanden die nur noch testet werden muss.

**Comment by Frozen-byte** [comment]
Wieso wurde dieses Issue geschlossen?

**Comment by GNCLORD-MDB** [comment]
weil fertig ist

**Comment by Frozen-byte** [comment]
Wo denn? Ich kann nicht nachvollziehen was es fertig gemacht hat.
