### ISSUE TITLE
Die Konfiguration der Fahrzeuge erzeugt keine Zusatzkosten im Budget.

### ISSUE THREAD

**Issue by GNCLORD-MDB** [OperationPandoraTrigger/OPT-Server-Mod#75]
Betreffenes Fahrzeug soll der Kuma sein

**Comment by GNCLORD-MDB** [comment]
Verstehe ich nicht ?????

**Comment by Frozen-byte** [comment]
Laut Zocker war es der Kuma, wo die Konfiguration nicht korrekt berechnet wird.

**Comment by GNCLORD-MDB** [comment]
OK dann teste ich spezielle den Kuma nochmal r

**Comment by GNCLORD-MDB** [comment]
im log ist ein vermerk das dem wieder spricht 
21:30:20 "[OPT] (Budget) Log: 1:21:12 --- AAF alt: 2.195e+06 - neu: 1.98e+06 - Differenz: -215000. Zocker mag Gelir inLatex (ver)kaufte MBT-52 Kuma"

und extra getestet hab ich auch noch und es wir berechnet.

**Comment by Frozen-byte** [comment]
Genau da hätten 510000 stehen müssen, da Zocker in der Konfiguration überall das Teuerste gewählt hat.

**Comment by GNCLORD-MDB** [comment]
100K kostet der Kuma und das steht als Minus auch da.

**Comment by Frozen-byte** [comment]
Dann stimmt der Angezeigte Preis im Mod nicht:
![image](https://user-images.githubusercontent.com/3965439/89923243-98ce7780-dc00-11ea-8126-675af818aca2.png)

**Comment by GNCLORD-MDB** [comment]
Das ist Grundpreis + Bewaffnung

**Comment by Frozen-byte** [comment]
hm... Etwas ungeschickt, finde ich da es nicht ersichtlich ist wie sich der Preis zusammen setzt.

Ich denke mir mal was aus, wie man das Transparenter gestalten kann.

**Comment by Frozen-byte** [comment]
Wenn man auf "Konfigurieren" klickt weiß man nicht was die "Standardbewaffnung" ist. Da die Felder alle leer sind.
Die Felder vorbefüllt zu lassen ist auch doof, da ich in dem Moment, wo ich auf "Konfigurieren" klicke mich schon dazu entschieden habe eine Indivuelle Bewaffnung zu haben.

Wie sieht es mit Hover-Elementen aus? Kann man vielleicht über den button mit der Maus fahrne und bekommt dann eine schöne Kostenaufstellung?

Dachte da an sowas (preise sind nur repräsentativ)
Object | Anzahl | Kosten
------------ | -------------|-------
Chassis | 1x  | -100.000
APFSD |    16x   | -5.000
HE |          12x  | -5.000
Datalink | 1x | -10.000
  |  | 
Gesamt | | -365.000

**Comment by GNCLORD-MDB** [comment]
So einen hover habe ich noch nie gesehen.
Es gibt ne hover, aber ob der in der Lage ist anzuzeigen weiss ich nicht. Und die nötigen Daten dafür ist auch kein kleiner Aufwand.

Sollten diese Details nicht auf ein HTML Seite in forum drin stehen. Dort wo jetzt der alte Pool noch drin steht?

**Comment by GNCLORD-MDB** [comment]
Also ich könnte über 7 Ecken das schaffen die Daten zu erlangen wo die Maus ist. Dann aber weiß ich wie ich das anzeigen soll, da kenne ich keine Möglichkeit was beim Button anzuzeigen.

**Comment by GNCLORD-MDB** [comment]
man kann vielleicht die Möglichkeit ein Hover zu erstellen, den kann man aber nicht so schön formatieren wie bei den vorschlagt , das ist ein Einzeiller der dann sehr lang wird und über den Bildschirm läuft.
Das könnte man das darstellen dann, mehr Text würde das glaube ich nicht besser machen.

![image](https://s12.directupload.net/images/200812/hwdrk6ls.jpg)

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
