### ISSUE TITLE
Die Selbstheilung funktioniert nicht korrekt?

### ISSUE THREAD

**Issue by Frozen-byte** [OperationPandoraTrigger/OPT-Server-Mod#78]
Sollte eigentlich soweit heilen dass alle "Verletzterscheinungen" entfernt werden (Humpeln, Stöhnen, Wackeln, Sicht)

Nur ein Medic kann jedoch auf 100% heilen.

**Comment by gelir95** [comment]
Da fehlt ne genau Beschreibung. Was ist 100% ab wann soll humpeln usw weg sein?

**Comment by Frozen-byte** [comment]
Selbsheilung soll nur die Symptome einer Verletzung beheben.
Ein Medic soll einen Spieler wieder auf den Stand bringen, als wäre er frisch gespawnt.

Ich kenne die exakte Aufteilung aktuell nicht ab wann ein Spieler humpelt oder ähnliche Verletzungssymptome aufweist, daher die Wage Beschreibung.

War der Meinung, das Konzeptteam hätte es bereits definiert wann was passiert. Lass uns das einmal im TeamSpeak klären und das Fazit hier festhalten.

**Comment by GNCLORD-MDB** [comment]
Ein Spieler humpel wenn er eine Verletzung am Bein hat. Die selbst Heilung solle alle Verletzungen heilen. Die ACE funktion die wir nutz sollte das gewährleisten.
als test ob die ACE Funktion ein Bug hat nur ein fehl info ist.

**Comment by gelir95** [comment]
Genau und das teilweise heilen geht nicht dies wurde auch schon mehrfach erklärt und muss nur an die Spieler kommuniziert werden.

**Comment by GNCLORD-MDB** [comment]
Den Medizin Mann würde ich gerne in Schrank lassen und nicht versuchen ACE zu überzeugen das wir erfolgreich sind in ACE herum zu fummeln.

**Comment by GNCLORD-MDB** [comment]
geschlossen, bearbeitet
