### ISSUE TITLE
buildMod-Scripte pfadunabhängig machen.

### ISSUE THREAD

**Issue by WGPSenshi** [OperationPandoraTrigger/OPT-Server-Mod#9]
**Is your feature request related to a problem? Please describe.**
Wenn man die .bats aus anderen Pfaden ausruft (z.b. aus dem Basis-verzeichnis via .\tools\scripts\buildModAll.bat), kommt es zu File-Not-Found-Fehlern, weil die relativen Pfade in der Bat nicht mehr passen.

**Describe the solution you'd like**
Relative Pfade fixen ;) .

**Describe alternatives you've considered**
Keine

**Additional context**
Wäre wertvoll, weil man dann in VSCode sehr einfach Build-Tasks konfigurieren könnte, die man dann laientauglich per Knopfdruck auslösen kann. Später könnte man ganz luxuriös drüber nachdenken, einen filewatcher dazu zu packen, der das automatisch onSave triggert.

Zusätzlich noch eine Variable (gerne auch arg) für das Zielverzeichnis, und die Devs können komfortabel ihr Game-Mod-Verzeichnis als Ziel angeben und direkt dahin builden.  Gehört zwar in ein eigenes Issue, aber ich bin faul, und vielleicht machst du es ja auch so :> .

**Comment by Krzmbrzl** [comment]
> Relative Pfade fixen ;) .

Das Problem ist, dass der einzige "Fix" dafür das Verwenden aboluter Pfade wäre. Wenn man das ber verwendet, dann muss jeder die Skripte speziell an sein System anpassen. Das ist glaube ich noch schlechter.

Das einzige, das mir dazu einfallen würde, wäre zu versuchen, den absoluten Pfad zum aufgerufenen Skript auszulesen (bzw. uz schauen ob und wie das geht) und anhand dessen dann einen absoluten Pfade generieren. Da muss ich mal schauen :thinking:

**Comment by WGPSenshi** [comment]
Muss kein absPath sein.
`%~dp0` ist die Variable für den Ordner, in dem sich die Skriptdatei aufhält.

https://stackoverflow.com/questions/3827567/how-to-get-the-path-of-the-batch-script-in-windows

Den VSCode-Kram übernehm ich, keine Sorge.

**Comment by WGPSenshi** [comment]
See #10

**Comment by GNCLORD-MDB** [comment]
das tasks.json läuft bei mir in VSC nur so , "command": "./tools/scripts/buildModAll.bat",
alles andere führt nur dazu das nichts passiert aber das Programm läuft durch.

**Comment by formtapez** [comment]
Ist das Problem noch aktuell?
Wenn ja, wie kann man es nachstellen? (Definiere "alles andere")
